kind = "web"
previewPath = "/"
title = "EEW Website"
version = "1.0.0"
id = "artifacts/eew-website"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 25412

[services.development]
run = "pnpm --filter @workspace/eew-website run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/eew-website", "run", "build" ]
publicDir = "artifacts/eew-website/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "25412"
BASE_PATH = "/"
